apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}-deploy
  labels:
    app: {{ .Values.name }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
    spec:
      containers:
        - name: {{ .Values.name }}
          image: ghcr.io/dr666m1/probability_distribution_app:latest
          imagePullPolicy: Always # not recommended
          securityContext:
            runAsNonRoot: true
            capabilities:
              drop: ["all"]
            allowPrivilegeEscalation: false
          ports:
          - containerPort: 8501
          resources:
            requests:
              memory: "100Mi"
              cpu: "100m"
            limits:
              memory: "300Mi"
              cpu: "250m"
          livenessProbe:
            httpGet:
              path: / # /healthz is often used
              port: 8501
            initialDelaySeconds: 60
            periodSeconds: 300
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values: [{{ .Values.name | quote }}]
              topologyKey: kuernetes.io/hostname
