apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ .Values.name }}-ing
  labels:
    app: {{ .Values.name }}
  annotations:
    ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix # any path under "/"
        backend:
          serviceName: {{ .Values.name }}-svc
          servicePort: 8501

