apiVersion: v1
kind: LimitRange
metadata:
  name: distribution-limitrange
  label:
    app: distribution
spec:
  limits:
  - default: # you can override by containers.resouces.limits
      cpu: "250m"
      memory: "300Mi"
    defaultRequest: # you can override by containers.resouces.requests
      cpu: "100m"
      memory: "100Mi"
    type: Container

