apiVersion: v1
kind: Service
metadata:
  name: distribution
  namespace: distribution
  labels:
    app: distribution
spec:
  ports:
  - port: 8501
    protocol: TCP
    targetPort: 8501
  selector:
    app: distribution
  type: NodePort
